version: '3'
services:
    hornet-docker:
        build:
            context: ./hornet-docker
            dockerfile: Dockerfile
        ports:
            - "15600:15600"
            - "14265:14265" 
            - "14626:14626"
            - "8081:8081"
            - "2222:222"
    node-docker1:
        build:
            args:
                HORNETADDRESS: "hornet"
            context: ./node-docker
            dockerfile: Dockerfile
        ports:
            - "15601:15600"
            - "14266:14265" 
            - "14627:14626"
            - "8082:8081"
            - "2223:222"
            - "4002:4001"
        volumes:
            - ./scripts:/app/nodeapp/scripts
        links:
            - "hornet-docker:hornet"
