version: '3'
services:
    node-docker:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - HORNETADDRESS=EPJIAUDZOJGYNHPCEOLMTHEJPVDFGKUAIQO99M9ZGQO9KITPTWCSKCSHAOHZWNZHBXN99VMYT9POAXBYC
        volumes:
            - ../scripts:/app/nodeapp/scripts
        network_mode: host